name: Reusable Build Workflow

on:
  workflow_call:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Application
        run: |
          echo "Building Application..."
          echo "Reusable Workflow Executed Successfully"
